torchrun --standalone --nproc_per_node=1 train_gpt.py
torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.1
torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.01
torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.001
torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.0001
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.00001
torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.5
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.1
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.01
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.001
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.0001
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.00001
# torchrun --standalone --nproc_per_node=8 train_gpt.py --dropout_prob 0.000001
